### ISSUE TITLE
new \fpdi\FPDI() not working

### ISSUE THREAD

**Issue by rodrigotavio91** [hanneskod/fpdi#12]
I am trying to instaciante the FPDI class using new \fpdi\FPDI() and I just getting the error Class 'fpdi\FPDI' not found. I'm using this class inside a ZF2 project, but I used another projects in that way before, and worked. 
I also tried to use require_once just for tests, passing the path of the class FPDI, and I get the error Fatal error: Class 'fpdi\FPDF_TPL' not found. This seems to me that the namespaces are not working, but I don't know why.
I used composer to install.

**Comment by rodrigotavio91** [comment]
Sorry, just now I found that the error was with my composer.

**Comment by hanneskod** [comment]
It happens :smile:
