### ISSUE TITLE
Can't find WriteHTML

### ISSUE THREAD

**Issue by koenhendriks** [hanneskod/fpdi#15]
How can i use the WriteHTML function from FPDF with FPDI ?

I'm trying to write html on an existing pdf like this:

```php
        $backgroundPdf = 'path/to/file.pdf';
        $fpdi = new \fpdi\FPDI();
        $fpdi->setSourceFile($backgroundPdf);
        $source = $fpdi->importPage(1,'/MediaBox');
        $fpdi->addPage();
        $fpdi->useTemplate($source,0,0,0,0,true);
        $fpdi->writeHTML('<b>test</b>');
        $fpdi->Output();
```

But it shows a fatal error:

``` Call to undefined method fpdi\FPDI::writeHTML() ```

**Comment by hanneskod** [comment]
`writeHTML` is not a standard fpdf function. Use `write` for this.

Please see http://www.fpdf.org/
