### ISSUE TITLE
Unexpected data in xref table

### ISSUE THREAD

**Issue by mdunbavan** [hanneskod/fpdi#18]
Hi,

We've been using the package in a laravel 4.1 app and we've hit the above issue.

My local version is running a vagrant box with Homestead and php 5.6 and the pdfs generate easily and well and all is good. As soon as I move the site over to staging the site gives the error above. The staging server is running pretty much exactly the same as my local site dev environment.

What could the issue be?

Thanks,
Mark

**Comment by hanneskod** [comment]
Hi and thanx for reporting!

This sounds like a problem related to the fpdi core, and as such should be directed to setasign.

http://www.setasign.com/products/fpdi/about/

Closing as this is not directly related to this fork.
