### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by jacob-v-dam** [hanneskod/fpdi#19]
Hello,

I use laravel homestead with PHP 7.1. This gives me an 502 bad gateway error, with the following error:
` *62 recv() failed (104: Connection reset by peer) while reading response header from upstream`

This happens when I construct FPDI, nothing happend yes just: `$this->fpdi = new FPDI();`. This is the point where the composer package (`1.5.2-patch1`) is called.

I'm running laravel homestead, PHP 7.1 with Nginx. Any suggestions?

**Comment by tandrus-mc** [comment]
fpdf/fpdi is incompatible with php7.1 you need to revert back to 7.0 and your issue should be resolved.

**Comment by hanneskod** [comment]
Hi and sorry for the late reply!

Some short questions: did you try the latest version as well (1.6.1)? Are you able to reproduce using a comandline script?

I see no reason why fpdi and php7.1 should be incompatible as such.

I see new that this is discussed in many places. Please check out https://github.com/Setasign/FPDI/issues/13:

> Did you checked if you can reproduce the issue if opcache.enabled is set to 0?
>
> This statement from @tandrus-mc makes me think that it is opcache related (as also the bug report):
>
> > Oddly enough if I change something in fpdf class, save it and rerun it it works once.
>
> Can you verify this?

**Comment by hanneskod** [comment]
Closing as further discussions should live in the setasign repo.
