### ISSUE TITLE
Include support for \fpdf\FPDF_EXTENDED 

### ISSUE THREAD

**Issue by Konafets** [hanneskod/fpdi#9]

**Comment by hanneskod** [comment]
Closing this as there seems to be no development.

Suggested changes on fpdi itself should go directly to [setasign](http://www.setasign.com/products/fpdi/about/).

**Comment by lanort** [comment]
If anyone else struggling with this stumples upon this issue: This worked for me:

```php
<?php
    class FPDF extends \fpdf\FPDF_EXTENDED {}
    $pdf = new \fpdi\FPDI();
    //...
```

**Further help:**
 * http://www.fpdf.org/en/script/script92.php
 * [FPDI and tPDF](http://www.setasign.com/products/fpdi/demos/tfpdf-demo/)
